version: '3'

services:
  discord_edgegpt:
    build: .
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - BING_COOKIES=${BING_COOKIES}
      - MENTION_CHANNEL_ID=${MENTION_CHANNEL_ID}
      - IMAGE_TIMEOUT=${IMAGE_TIMEOUT}
      - IMAGE_MAX_CREATE_SEC=${IMAGE_MAX_CREATE_SEC}
      - COOKIES_SETTING_CHANNEL_ID=${COOKIES_SETTING_CHANNEL_ID}
      - DALLE3_SETTING_CHANNEL_ID=${DALLE3_SETTING_CHANNEL_ID}
      - CHAT_CHANNEL_ID=${CHAT_CHANNEL_ID}
      - CREATE_IMAGE_CHANNEL_ID=${CREATE_IMAGE_CHANNEL_ID}
      - RESET_CHAT_CHANNEL_ID=${RESET_CHAT_CHANNEL_ID}
      - HELP_CMD_CHANNEL_ID=${HELP_CMD_CHANNEL_ID}
    volumes:
      - ./cookies.json:/bot/cookies.json