version: '3'

services:
  discord_edgegpt:
    build: .
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - MENTION_CHANNEL_ID=${MENTION_CHANNEL_ID}
    volumes:
      - ./cookies.json:/bot/cookies.json